#!/bin/bash

# Total RAM
MEM=$(grep MemTotal /proc/meminfo | awk '{print $2}')

# Work memory
WM="32MB"

# Shared buffers is 20% of RAM up to 2GB, 25% up to 64GB, and a 16GB ceiling
if [ "$MEM" -lt 2097152 ]; then
  SB="$( printf %.0f $(("$MEM" / 5125)) )MB"
elif [ "$MEM" -lt 67108864 ]; then
  SB="$( printf %.0f $(("$MEM" / 4096)) )MB"
else
  SB="16GB"
fi

# Maintenance work memory is the lesser of 1GB or 10% of total RAM
MWM="$( printf %.0f $(("$MEM" / 10240)) )"
if [ "$MWM" -gt 1048576 ]; then
  MWM="1GB"
else
  MWM="${MWM}MB"
fi

# Effective cache size is set to 75% of total memory (file cache)
ECS="$( printf %.0f $(("$MEM" * 3 / 4096 )) )MB"

# If it's an AWS instance…
if [ -f /sys/hypervisor/uuid ] && [ `head -c 3 /sys/hypervisor/uuid` == ec2 ]; then
  RPC="random_page_cost = 1.1"
else
  RPC="random_page_cost = 3.0"
fi

cat << EOF
shared_buffers = $SB
work_mem = $WM
maintenance_work_mem = $MWM
effective_cache_size = $ECS
wal_buffers = 16MB
checkpoint_completion_target = 0.9
checkpoint_timeout = 10min
min_wal_size = 512MB
max_wal_size = 2GB
$RPC
EOF
